[workspace]

members = [
    "joystick-mapper-lib",
    "joystick-mapper-among-us",
    "joystick-mapper",
    "opencv-sys"
]

[patch.crates-io]
enigo = { git = "https://github.com/enigo-rs/enigo", rev = "5bb84e938009385987875472adafaa45613b3534" }

[profile.release]
opt-level = 0
